path: /data/ZJC/智能三轮车/datasets_v3.0
train:
  - data/fcw/images/bdd100k/train
  - data/fcw/images/nuscenes_mini/train
val:
  - data/fcw/images/bdd100k/val
  - data/fcw/images/nuscenes_mini/val
names:
  0: person
  1: rider
  2: car
  3: truck
  4: bus
  5: train
  6: motor
  7: bike
  8: obstacle
